# Generated by Django 5.0.6 on 2024-05-29 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sixthApp', '0002_student_father_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudetModel',
            fields=[
                ('roll', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('father_name', models.CharField(max_length=30)),
                ('address', models.TextField()),
            ],
        ),
    ]
